### ISSUE TITLE
Broken backwards compatibility

### ISSUE THREAD

**Issue by kapec94** [MIT-LCP/wfdb-python#107]
Just wanted to let you know that the new version of package has broken backwards compatibility. I do realize that this is a major bump in version (2.0.1, compared to previous 1.3.9), but there was no warning this would happen, as far as I can remember.  

There were no deprecations, no warnings. In the new version some functions are _gone_, to be replaced by other. And those aren't even big changes, but rather functions changing name (from API perspective at least). 

It's not a big issue really, just an inconvenience. I just want to give you some feedback. You could save people some time by just deprecating old functions first. Or don't just go around changing functions' names when there's no real need for that.

**Comment by cx1111** [comment]
Thanks for the deprecation/warning suggestion. I'll do that before a major version change next time.

I do change function names to be consistent with coding conventions to make things easier for me to write and maintain.

**Comment by gauravbrd** [comment]
This is really an issue for me, Due to lack of backward compatibility, I have to repair few stuff to get along with new version. But I believe, In future, This updated version will save us from many bugs 1.3.9 had and gives much more flexibility. Thanks

**Comment by Dubrzr** [comment]
This is an open source project with only a single major contributor, be happy to already have something that works quite fine! It's not like it has 10 active contributors that work full time on this. It is maybe not perfect but if you don't want to have to repair stuff at every update, just stay with the version that works for you. If new features are available in a more recent version and API changes breaks your code that's because we needed to change the API. About the deprecation/warning, it is fine for really big projects where you have a schedule for the development etc but in the real life with such small packages when you have an idea to improve the code you develop it in like an afternoon and you don't have the time to create a new release just to add warnings. You can also pip install from commits if you want to update to specific commits that fix your problems (https://stackoverflow.com/questions/13685920/install-specific-git-commit-with-pip).
