### ISSUE TITLE
resample_ann can get stuck under some certain conditions

### ISSUE THREAD

**Issue by wfel** [MIT-LCP/wfdb-python#116]
Using record 223 and the annotation file generated by ecgpuwave with
```
ecgpuwave -r 223 -a pqrst -i atr
```
the resample_multichan can get stucked
```
rec = wfdb.io.rdrecord('223')
ann = wfdb.io.rdann('223', 'pqrst')
wfdb.processing.resample_multichan(rec.p_signal, ann, rec.fs, fs_target=250)
```
due to resample_ann.

Here are the files:
https://drive.google.com/file/d/1IWQ0ijl2c20hkDUOdHWPpgjqxoOsdcKG/view?usp=sharing

**Comment by Lucas-Mc** [comment]
I just made a pull request #210 to fix this issue. It appears like the algorithm used in `resample_ann` was developing an infinite loop. After some investigation, I think this is caused by setting the `fs_target` too high as seen by the following chart which displays the `fs_target` on the x-axis and the number of infinite loops on the y-axis:
![Infinite_Breaks](https://user-images.githubusercontent.com/39505798/81315805-c4b5ec00-9058-11ea-97ae-b1c5590dbcc0.png)
The code you posted here works now after these changes. Thanks for posting it here!
