### ISSUE TITLE
Why sometimes wfdb.rdann() arises ValueError: cannot reshape array of size xxx into shape (2)

### ISSUE THREAD

**Issue by Yang-LONG** [MIT-LCP/wfdb-python#167]
When I use wfdb.rdann() for reading a .hea file, a ValueError usually comes out saying 'cannot reshape array of size xxx into shape (2)'. 

For instance, I want to read a103l (https://physionet.org/physiobank/database/challenge/2015/training/)
```python
ann = wfdb.rdann('a103l',sampfrom=0,sampto=None,extension='hea')
```
It returns:
"ValueError: cannot reshape array of size 195 into shape (2)."

However, if I input 109l,
```python
ann = wfdb.rdann('a109l',sampfrom=0,sampto=None,extension='hea')
```
It works.

So I found that whether this problem arises or not is depend on data, some .hea do but others do not. I wonder if it is a general problem? Does anyone have the same question? Or is there a solution already?

**Comment by gabett** [comment]
I'm experiencing the same problem as well.

**Comment by Lullatsch** [comment]
Did someone find a solution to this yet?

**Comment by vishwas1234567** [comment]
In the making.

**Comment by vishwas1234567** [comment]
But randn will work try with it documentation reference will also say the
same look for it once.

**Comment by Lucas-Mc** [comment]
Hello all, thank for the inquiry! Note that `rdann` is only used to run annotation files. See the docstrings here where the extension it used to describe different annotation extensions (e.g. "atr", "anI", etc.):

https://github.com/MIT-LCP/wfdb-python/blob/0d4b5a689bc7a1719af1ead6e6dd5b1ecaf1a6b3/wfdb/io/annotation.py#L1196-L1210

The correct function that you want in order to read a ".hea" file would be `rerecord`. Simple run `wfdb.rdrecord('a103l')` and you will get an object containing the signal and various other attributes (format, name, units, etc.). 

I believe it is merely coincidence that it runs for some ".hea" files because it ideally shouldn't for any! Maybe I can raise and exception if ".hea" is called as an extension?
