### ISSUE TITLE
pb_dir path error

### ISSUE THREAD

**Issue by phaniparsa** [MIT-LCP/wfdb-python#212]
Hello,

I'm trying to read "p000020-2183-04-28-17-47n.hea" file at https://physionet.org/content/mimic3wdb-matched/1.0/p00/p000020/ using the below command but ending up getting an error.

Command: signals2, fields2 = wfdb.rdsamp('p000020-2183-04-28-17-47n', pb_dir='https://physionet.org/content/mimic3wdb-matched/1.0/p00/p000020/')

Error:
HTTPError: 404 Client Error: Not Found for url: http://physionet.org/physiobank/database/https://physionet.org/content/mimic3wdb-matched/1.0/p00/p000020/p000020-2183-04-28-17-47n.hea

Appears that rdsamp kind of prefixes "http://physionet.org/physiobank/database/" to whatever the value that I'm giving to pb_dir. 

I tried the below command as well:
signals2, fields2 = wfdb.rdsamp('p000020-2183-04-28-17-47n', pb_dir='mimic3wdb-matched/1.0/p00/p000020/')

and got the below error:
HTTPError                                 Traceback (most recent call last)
<ipython-input-29-0006afdb6611> in <module>
      1 # Can also read the same files hosted on Physionet
----> 2 signals2, fields2 = wfdb.rdsamp('p000020-2183-04-28-17-47n', pb_dir='mimic3wdb-matched/1.0/p00/p000020/')

~\Anaconda3\lib\site-packages\wfdb\io\record.py in rdsamp(record_name, sampfrom, sampto, channels, pb_dir, channel_names, warn_empty)
   1392                       sampto=sampto, channels=channels, physical=True,
   1393                       pb_dir=pb_dir, m2s=True, channel_names=channel_names,
-> 1394                       warn_empty=warn_empty)
   1395 
   1396     signals = record.p_signal

~\Anaconda3\lib\site-packages\wfdb\io\record.py in rdrecord(record_name, sampfrom, sampto, channels, physical, pb_dir, m2s, smooth_frames, ignore_skew, return_res, force_channels, channel_names, warn_empty)
   1152 
   1153     # Read the header fields
-> 1154     record = rdheader(record_name, pb_dir=pb_dir, rd_segments=False)
   1155 
   1156     # Set defaults for sampto and channels input variables

~\Anaconda3\lib\site-packages\wfdb\io\record.py in rdheader(record_name, pb_dir, rd_segments)
    989     # Read the header file. Separate comment and non-comment lines
    990     header_lines, comment_lines = _header._read_header_lines(base_record_name,
--> 991                                                              dir_name, pb_dir)
    992 
    993     # Get fields from record line

~\Anaconda3\lib\site-packages\wfdb\io\_header.py in _read_header_lines(base_record_name, dir_name, pb_dir)
    726     else:
    727         header_lines, comment_lines = download._stream_header(file_name,
--> 728                                                               pb_dir)
    729 
    730     return header_lines, comment_lines

~\Anaconda3\lib\site-packages\wfdb\io\download.py in _stream_header(file_name, pb_dir)
     88 
     89     # Raise HTTPError if invalid url
---> 90     response.raise_for_status()
     91 
     92     # Get each line as a string

~\Anaconda3\lib\site-packages\requests\models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 404 Client Error: Not Found for url: http://physionet.org/physiobank/database/mimic3wdb-matched/1.0/p00/p000020/p000020-2183-04-28-17-47n.hea

is there a way to circumvent this prefix issue and give the complete path, such that data is read from the complete path?

Thanks!

**Comment by Lucas-Mc** [comment]
Hey @phaniparsa, here is the command that you should use to achieve your desired results:

`signal2, fields2 = wfdb.rdsamp('p000020-2183-04-28-17-47n', pn_dir='mimic3wdb-matched/p00/p000020')`

Unfortunately, the current release of WFDB on pip doesn't include any of the new databases posted on the Physionet site so this will have to be run after cloning the code locally. I am working on updating the pip to include this now. 

I think allowing the platform to run any link currently (include http and all) is not something I believe needs to be developed right now but it can be up for debate. It would be difficult to sort out correct links and the current platform allows users to just select the desired database and file and it will automatically find the correct link instead of searching for it yourself. I guess, as in your case, if you want to work backwards then this would be helpful. Again, up for debate at the moment!

**Comment by phaniparsa** [comment]
Hey @Lucas-Mc  thank you for the reply.

When ran the above line, I got the below error:
TypeError                                 Traceback (most recent call last)
<ipython-input-5-238e2a71041c> in <module>
----> 1 signal2, fields2 = wfdb.rdsamp('p000020-2183-04-28-17-47n', pn_dir='mimic3wdb-matched/p00/p000020')

TypeError: rdsamp() got an unexpected keyword argument 'pn_dir'

Hence, tried with pb_dir as well, but the below error:
HTTPError: 404 Client Error: Not Found for url: http://physionet.org/physiobank/database/mimic3wdb-matched/p00/p000020/p000020-2183-04-28-17-47n.hea

Should I downgrade wfdb to any previous versions, to mitigate this error?

**Comment by Lucas-Mc** [comment]
It is not possible to read the `mimic3wdb-matched` database on any release of WFDB from `pip install`. The only way is to use the code in this repository and then it should recognize the `pn_dir` argument. Hopefully within the next week or so, it will be available on `pip install`. Thanks!

**Comment by Lucas-Mc** [comment]
I should add that the reason for this is because, currently, all of the data is trying to be read from Physiobank so only the databases on that website can be accessed. However, the updated code in this repository and the soon-to-come `pip install` will take its data from Physionet which includes the Physiobank projects as well as all the new ones.

**Comment by phaniparsa** [comment]
Hey @Lucas-Mc ,

Thank you for the reply. I installed the dev. version of wfdb and able to use "pn-dir" now. Thank you very much for your time, explanation and patience :)

**Comment by Lucas-Mc** [comment]
Hey @phaniparsa, you should be able to subscribe to updates here: https://libraries.io/pypi/wfdb. Let me know if it doesn't work!

**Comment by phaniparsa** [comment]
Hi @Lucas-Mc  it works, thank you very much.
