### ISSUE TITLE
wfdb documentation page is not working proper

### ISSUE THREAD

**Issue by AryaVerma** [MIT-LCP/wfdb-python#227]
There is some issue with wfdb documentation page , i cant find the functions related to wfdb record and download on this page .

**Comment by AryaVerma** [comment]
Also while reading the records using rdasmp, why dont we get time and date column?

**Comment by Lucas-Mc** [comment]
Hey @AryaVerma, I think the issue with the builds is that in `MOCK_MODULES` I haven't added the latest package from the PR yesterday `MNE` so a lot of the content isn't importing properly. I will fix the documentation now! In the meantime, you can use the latest stable build [here](https://wfdb.readthedocs.io/en/stable/). 

As for your other issue, I will look into it following the documentation fix and get back with you! 👍

**Comment by Lucas-Mc** [comment]
Documentation has been fixed!

**Comment by Lucas-Mc** [comment]
Hey @AryaVerma, regarding your other question, the time is given in the form of `fs` which is the sample rate. After processing, each signal will have the same sample rate. This saves spaces instead of saving an entire `numpy` array of time data which could just be determined using: `np.arange(0, record.sig_len/record.fs, 1/record.fs)`. You can see that this works here...

With samples ... `wfdb.plot_wfdb(record=record, time_units='samples')`:
![ECG_Samples](https://user-images.githubusercontent.com/39505798/83880475-31caa900-a70d-11ea-9785-1add83aebf2f.png)

With seconds ... `wfdb.plot_wfdb(record=record, time_units='seconds')`:
![ECG_Seconds](https://user-images.githubusercontent.com/39505798/83880503-3c853e00-a70d-11ea-9ec2-3a938cb05982.png)
