### ISSUE TITLE
Database download fails on windows

### ISSUE THREAD

**Issue by dennis95stumm** [MIT-LCP/wfdb-python#247]
If i try on windows run a database download with something like that:

```python
import wfdb
import os

wfdb.dl_database('ahadb', os.path.join('C:', 'db'))
```
 I get a 404 error because a \ is always added at the end of url as %5C, what is the path separator url encoded, which gets wrongly added to the url here: https://github.com/MIT-LCP/wfdb-python/blob/master/wfdb/io/record.py#L3384

**Comment by dennis95stumm** [comment]
It would also be good if the csv-Files that contains classification information (for example REFERENCE-SQI.csv in the `challenge-2016/training-a` db which contains additional classification, which isn't included in the wfdb-headers) would be downloaded with this command.

**Comment by Lucas-Mc** [comment]
Hey @dennis95stumm, thanks for posting this! Yeah it looks like a silly mistake on my end when switching from Physiobank to PhysioNet that wasn't caught since it was being tested on Linux and OSX (Windows is weird) so I'll post the fix soon!

Downloading the CSV files and other files seems out of the scope of this package since it is only meant to extract the WFDB-compatible files such as RECORDS, ANNOTATORS, .dat, .hea, etc. If you wish to download all the files, you should use the `wget` command or one of the other options from the PhysioNet website, thanks!
