### ISSUE TITLE
Download DB on ltafdb directs to a 404.

### ISSUE THREAD

**Issue by khtad** [MIT-LCP/wfdb-python#252]
This code:

import wfdb
import os

def main():
db = 'ltafdb'
wfdb.dl_database(db_dir=db,
dl_dir=os.getcwd())

if name == 'main':
main()

returns the following error:

Traceback (most recent call last):
File "C:/wfdbAFIB/downloadDB.py", line 12, in
main()
File "C:/wfdbAFIB/downloadDB.py", line 8, in main
dl_dir=os.getcwd())
File "C:\Users\micha\Anaconda3\lib\site-packages\wfdb\io\record.py", line 2253, in dl_database
r.raise_for_status()
File "C:\Users\micha\Anaconda3\lib\site-packages\requests\models.py", line 940, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://physionet.org/content/ltafdb/1.0.0%5C/

The URL that the subroutine is pointing at is indeed 404 because the DB has been moved to https://archive.physionet.org/physiobank/database/ltafdb/.

**Comment by Lucas-Mc** [comment]
Hey @khtad, the database does exist on the existing PhysioNet site here: https://physionet.org/content/ltafdb/1.0.0/. The issue you are experiencing is the addition of the `%5C` in the URL for Windows machines due to a bug in the code. This issue was fixed on #251 and your issue should be resolved with an update to the latest code. Thanks!
