### ISSUE TITLE
Blood pressure labels for each waveform

### ISSUE THREAD

**Issue by StanleyGan** [MIT-LCP/wfdb-python#277]
Hi there, I am planning to work with PPG signals and I am trying to get the corresponding blood pressure for each segment (if it's available). The database which I am working with is: https://physionet.org/content/mimic3wdb/1.0/31/. 

For example for patient 31/3100011, segment 3100011_0002, I ran 
```
rec = wfdb.rdsamp("31/3100011_0002")
```
and I am assuming `rec[0][:,1]` corresponds to PPG signal since `rec[1]['sig_name'][1]` has `PLETH` as indicator. It is mentioned that `3100011n.dat` contains the numeric measurements for the patient. Using `wfdb.rdsampl()` again, I got an array and a description of the data. I am assuming the blood pressure is one of the columns of the array. The question is how do I match it to a particular segment?

**Comment by Lucas-Mc** [comment]
Hey @StanleyGan, thanks for asking! The details are explained in the MIMIC3 WDB [usage notes](https://physionet.org/content/mimic3wdb/1.0/#usage-notes),  but the basic overview is that each record (`3100011_0001`, `3100011_0002`, etc.) represent a segment of signal collected during patient `31`'s stay. The numerics record (`*n.dat`, `*n.hea`) should cover most of the record times as indicated by its starting time (`base_time`) and its length (`sig_len / fs`). You can overlay each signal given its starting time and length after setting down the numerics.

It may be better to contact `mimic-support@physionet.org` since this is more of a MIMIC question than WFDB.
