### ISSUE TITLE
wfdb.rdsamp for reading cerebral perfusion database

### ISSUE THREAD

**Issue by arjun-subramaniyan** [MIT-LCP/wfdb-python#307]
While trying to read the records from the cerebral perfusion database at https://physionet.org/content/cerebral-perfusion-diabetes/1.0.0/ which contains ecg in the form of .dat and .hea records, a time value error throws up.
![image](https://user-images.githubusercontent.com/57363072/122439163-08e42180-cfb9-11eb-9451-1c236a6255b0.png)

**Comment by cx1111** [comment]
@bemoody It looks like the header file's date field is just: "2006". https://physionet.org/content/cerebral-perfusion-diabetes/1.0.0/data/ecg/S0287ECG.hea

This doesn't appear to be valid: https://www.physionet.org/physiotools/wag/header-5.htm

How would the WFDB C package handle this?

**Comment by briangow** [comment]
@ arjun-subramaniyan thank you for alerting us to this issue. The header files for this project have been fixed in: https://physionet.org/content/cerebral-perfusion-diabetes/1.0.1/ . 

I will close this issue but further discussion on how handle these types of issues can be found at: https://github.com/MIT-LCP/wfdb-python/issues/415 .
