### ISSUE TITLE
Unexpected changes to checksum after `wrsamp`

### ISSUE THREAD

**Issue by briangow** [MIT-LCP/wfdb-python#449]
Simply reading an entire WFDB record and writing it without making any changes should result in a consistent checksum. However this is not the case with `wrsamp` (in v4.0.0). 

```
orig_record = wfdb.rdrecord('100', pn_dir='mitdb/1.0.0')
print(orig_record.checksum)
[-22131, 20052]
```
```
wfdb.wrsamp('python_wrsamp_100', orig_record.fs, orig_record.units, orig_record.sig_name, orig_record.p_signal)
python_wrsamp = wfdb.rdrecord('python_wrsamp_100')
print(python_wrsamp.checksum)
[55201, 4478]
```

**Comment by bemoody** [comment]
That's because wrsamp re-scales the samples; in this case, it picks a new `adc_gain` and `baseline` in order to fit the provided `p_signal` values into a 12-bit range.

I don't know exactly how this is done, but you would only expect the `checksum` to match if the `d_signal` values match (which would be the case if the `adc_gain` and `baseline` likewise match.)

**Comment by briangow** [comment]
Ok, thanks for the explanation.
