### ISSUE TITLE
Plot ECG signal with big box and small box 

### ISSUE THREAD

**Issue by RumbosN** [MIT-LCP/wfdb-python#45]
Posibility of when you plot ECG signal appear the big box and small box that identify ms like the image: http://www.e-projects.ubi.pt/smart-clothing/images/fig11.jpg

**Comment by cx1111** [comment]
I've added an option in the latest commit for plotrec:

`def plotrec(record=None, title = None, annotation = None, annch = [0], timeunits='samples', returnfig = False, ecggrids=False):`

Although the grids mess up the x axis label when the signal extends beyond a few seconds. Suggestions (from anyone) would be appreciated.

**Comment by Dubrzr** [comment]
I was thinking of using ax.xaxis.set_major_locator(plt.MultipleLocator(1)) but this does not give what we exactly want.

So I tried with simply ploting lines instead of matplotlib ticks and it give a pretty result while having good x axis labels:

![image](https://cloud.githubusercontent.com/assets/3718838/26177983/03be8916-3b2a-11e7-830c-1cddf39f124c.png)

Just put the following code after _ax = fig.add_subplot(nsig, 1, ch+1)_:
```
if ecggrids:
    major_ticks_x, minor_ticks_x, major_ticks_y, minor_ticks_y = calc_ecg_grids(
                record.p_signals[:,ch], record.units[ch], record.fs, t, timeunits)
    min_x, max_x = 0, numpy.max(t)
    min_y, max_y = np.min(record.p_signals[:,ch]), np.max(record.p_signals[:,ch])
    for tick in minor_ticks_x:
        ax.plot([tick, tick], [min_y,  max_y], c='#ededed', marker='|')
    for tick in major_ticks_x:
        ax.plot([tick, tick], [min_y, max_y], c='#bababa', marker='|')
    for tick in minor_ticks_y:
        ax.plot([min_x, max_x], [tick, tick], c='#ededed', marker='_')
    for tick in major_ticks_y:
        ax.plot([min_x, max_x], [tick, tick], c='#bababa', marker='_')
```

**Comment by cx1111** [comment]
I've updated it using your code. Thanks!
