### ISSUE TITLE
Suggestions for comparing floating point values in nosetests?

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/wfdb-python#8]
Some nosetests are failing because of the floating point comparisons. When I create the target text files using rdsamp, I get 8 decimal places. 

What else could I put aside from `assert np.array_equal(sig, targetsig)`?

**Comment by tompollard** [comment]
Hey Chen, see: http://stackoverflow.com/questions/4028889/floating-point-equality-in-python

Does numpy.testing.assert_allclose work?

Tom


Sent from my iPhone

On 19 Jul 2016, at 15:24, Chen Xie <notifications@github.com<mailto:notifications@github.com>> wrote:


Some nosetests are failing but it's because of the floating point comparisons. When I create the target text files using rdsamp, I can specify up to 8 decimal places.

What else could I put aside from assert np.array_equal(sig, targetsig)?
