### ISSUE TITLE
Issue installing wfdb on python 3.6

### ISSUE THREAD

**Issue by viggi1000** [MIT-LCP/wfdb-python#83]
Hi, I'm new to coding and I've run into some issues with installing the wfdb package on python. I'm getting this following error. Can someone point me to a fix?

I tried both pip install wfdb and downloading the repo and cd'ing to the folder and doing a pip install .

![image](https://user-images.githubusercontent.com/1295467/31859552-129cc2e0-b72b-11e7-8c45-43b651a90372.png)

**Comment by Dubrzr** [comment]
Uninstall Python, install Anaconda (https://www.anaconda.com/download/), use anaconda's Python and this should solve your issue as stated in this stackoverflow answer: https://stackoverflow.com/a/29860484

This is not a wfdb issue, when you have such problems, post them on stackoverflow rather than on wfdb issues. Also, try to type the error on google, for example "no lapack/blas resources found" to find solutions to your problem.

**Comment by viggi1000** [comment]
Thanks for your quick help but I'm facing the same issue in anaconda. I'll try the stackoverflow post and follow. I'll post further problems in Stackoverflow from here on out.
