### ISSUE TITLE
Changing API w/o new major version numbers is making maintenance difficult

### ISSUE THREAD

**Issue by kbrose** [MIT-LCP/wfdb-python#85]
Hello! First of all, thanks so much for the wonderful package!

I noticed that the API has changed substantially since I installed the library a few months ago. However, I was not expecting such major compatibility breaking changes because the version number had only been incremented by 0.0.1 !

I was wondering if you might consider trying to follow [semantic versioning](https://semver.org/) where possible. Although the system is not perfect, it can be practically useful to know when upgrading versions may break old code.

Thanks!

**Comment by cx1111** [comment]
Thanks for the reminder to follow the conventions. I'll try to be better about it.

I did change the major version number from 0 to 1 when introducing the Record/Annotation classes. But I realize now that I only incremented the minor version when I changed most of the variable names of the Annotation class.

Which API changes in particular are you referencing that broke your code? I ask because I have made many version number increases, definitely not just 0.0.1 since a few months ago. I don't think you're talking about github release versions because I've basically neglected that completely in favor of git tags.

**Comment by kbrose** [comment]
Yeah it was the annotation names that got me.

There's no [`__version__` number](https://www.python.org/dev/peps/pep-0396/) when I import the package, so I'm looking at the pip artifcats in my site-packages directory. That tells me I have 1.3.5, and it was installed around 11/7 -- I must have upgraded versions without remembering it, sorry for the confusion about the month**S** comment!

**Comment by cx1111** [comment]
Added __version__ to the package.
