### ISSUE TITLE
Resampling single channel

### ISSUE THREAD

**Issue by gauravbrd** [MIT-LCP/wfdb-python#97]
Hi All,
I am trying to resample singal channel signals with below code.

sig, fields = wfdb.srdsamp('221',sampto=1200, channels = [0], pbdir = 'mitdb' )
ecgann = wfdb.rdann('221', 'atr', sampto=1200, pbdir='mitdb')
new_sig, new_ann = wfdb.processing.resample_singlechan(x=sig[:, 0], ann = ecgann, fs=fields['fs'], fs_target=200)
display(new_sig)
display(ecgann.fs)
display(new_ann.fs)

As seen in above code, I am displaying pre- resampling 'fs' and post-resampling 'fs'. I see 360hz in both the cases. After resampling,  display(new_ann.fs) should print 200, as I have resampled with 200hz.  

Is there a way to double check the frequency after resampling has been done ?

-Thanks
Gaurav

**Comment by gauravbrd** [comment]
I made modification to basic.py, line 80
new_ann = Annotation(ann.recordname, ann.extension, new_sample, ann.symbol, ann.num, ann.subtype, ann.chan, ann.aux_note, fs_target)

So,fs_target should be setting the new annotation object's 'fs' field, instead of the previous sampling frequency(fs)

Correct me If I am wrong,

Thanks

**Comment by Dubrzr** [comment]
It seems correct to me that the new Annotation object should be setting the frequency to fs_target instead of the previous fs.
If you want to double check the resampling of the annotations associated with a resampled signal you have many options such as plotting the signal with its annotations before and after resampling, or maybe you can try to assert resample(resample(sig_360hz, 200), 360) == sig_360hz and resample(resample(ann_360hz, 200), 360) == ann_360hz.

**Comment by Dubrzr** [comment]
https://github.com/MIT-LCP/wfdb-python/commit/93ca1fe5a5b7f08be9c050955eb46a00b5ba2e93
